export const cardArray = [
  {
    id: 0,
    title: "Первый товар",
    price: "170",
    addres: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "./images/material.png",
  },
  {
    id: 1,
    title: "Второй товар",
    price: "171",
    addres: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "./images/material.png",
  },
  {
    id: 2,
    title: "Третий товар",
    price: "172",
    addres: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "./images/material.png",
  },
  {
    id: 3,
    title: "Четвертый товар",
    price: "173",
    addres: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "./images/material.png",
  },
  {
    id: 4,
    title: "Пятый товар",
    price: "174",
    addres: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "./images/material.png",
  },
  {
    id: 5,
    title: "Шестой товар",
    price: "177",
    addres: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "./images/material.png",
  },
];
